config/routes.rb
Rails.application.routes.draw do


  # Set Project Root Directory #
  root 'static_pages#home'

  # Set Project Base Pages #
  get 'about',     to: 'static_pages#about'
  get 'contact',   to: 'static_pages#contact'

  # Set User Directories #
  get    'signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'admin',    to: 'users#admin'
  get    'agency-information',   to: 'users#agency_information'
  post   'update-agency-information', to: 'users#rails_settings_setting_user', as: 'rails_settings_setting_user'
  patch   'update-agency-information', to: 'users#rails_settings_setting_user'

  # Set Project Resources #
  resources :users
  resources :submissions
  resources :business_infos
  get 'classcode/search', to: 'business_infos#search'

  post 'form-type', to: "submissions#form_type"
end

app/models/user.rb
class User < ApplicationRecord
  has_settings :agency_information
  has_many :submissions
  attr_accessor :remember_token

  # Before Saving Arguments #
  before_save { email.downcase! }

  # Validate Agent Agency #
  validates :agency, presence: true, length: { maximum: 100 }

  # Validate Agent Name #
  validates :name, presence: true, length: { maximum: 70 }

  # Validate Agency Code #
  # validates :agency_code, presence: true, length: { maximum: 4 }

  # Create Email REGEX #
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  # Validate Agent Email #
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  # Ensure Secured Password #
  has_secure_password

  # Validate Agent Password #
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # Returns a session token to prevent session hijacking.
  # We reuse the remember digest for convenience.
  def session_token
    remember_digest || remember
  end


  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def admin
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to B1 Technologies!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def agency_information
    @user = User.find(current_user.id)
    # binding.pry
    @user = @user.settings(:agency_information)
    # binding.pry

  end

  def rails_settings_setting_user
    @user = current_user
    @user.settings(:agency_information).producer_id = params[:rails_settings_setting_object][:producer_id]
    @user.settings(:agency_information).on_behalf_of = params[:rails_settings_setting_object][:on_behalf_of]
    @user.settings(:agency_information).producer_email = params[:rails_settings_setting_object][:producer_email]
    @user.settings(:agency_information).on_behalf_of_email = params[:rails_settings_setting_object][:on_behalf_of_email]
    @user.settings(:agency_information).agency_license_number = params[:rails_settings_setting_object][:agency_license_number]
    @user.settings(:agency_information).broker_license_number = params[:rails_settings_setting_object][:broker_license_number]
    @user.settings(:agency_information).agency_address = params[:rails_settings_setting_object][:agency_address]
    @user.settings(:agency_information).agency_address2 = params[:rails_settings_setting_object][:agency_address2]
    @user.settings(:agency_information).agency_city = params[:rails_settings_setting_object][:agency_city]
    @user.settings(:agency_information).agency_state = params[:rails_settings_setting_object][:agency_state]
    @user.settings(:agency_information).agency_zip_code = params[:rails_settings_setting_object][:agency_zip_code]
    @user.settings(:agency_information).agency_phone_number = params[:rails_settings_setting_object][:agency_phone_number]
    @user.settings(:agency_information).agency_fax_number = params[:rails_settings_setting_object][:agency_fax_number]
    @user.settings(:agency_information).save!
    flash[:success] = "Agency information has been updated"
    redirect_back(fallback_location: root_path)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:agency, :name, :email, :password, :password_confirmation, :agency_code)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/agency_information.html.erb
<% provide(:title, "Edit user") %>
<div class=" font-sans login bg-cover">
<div class="container mx-auto flex flex-1 justify-center items-center">
    <div class="w-full max-w-lg">
      <div class="leading-loose">
        <%= form_with(model: @user, local: true, url: rails_settings_setting_user_path, class: "max-w-sm m-4 p-10 bg-white bg-opacity-25 rounded shadow-xl") do |f| %>
          <%= render 'shared/error_messages' %>
          <p class="text-white font-medium text-center text-lg font-bold">Agency information</p>
          <div class="gap-3">
            <span class="w-1/2">
              <%= f.label :producer_id, class: "block  text-sm text-white" %>
              <%= f.text_field :producer_id, placeholder: "Producer ID", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).producer_id %>
            </span>
            <span class="w-1/2">
              <%= f.label :producer_agency, class: "block  text-sm text-white" %>
              <%= f.text_field :producer_agency, placeholder: "Producer Agency", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).producer_agency  %>
            </span>
            <span class="w-1/2">
              <%= f.label :producer_name, class: 'block text-sm text-white' %>
              <%= f.text_field :producer_name, placeholder: 'Producer name', class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).producer_name  %>
            </span>
          </div>
          <div class="gap-3">
            <%= f.label :on_behalf_of, class: "block  text-sm text-white" %>
            <%= f.text_field :on_behalf_of, placeholder: "On behalf of", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).on_behalf_of  %>
          </div>
          <div class="gap-3">
            <%= f.label :producer_email, class: "block  text-sm text-white" %>
            <%= f.text_field :producer_email, placeholder: "Enter producer email", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).producer_email %>
          </div>
          <div class="gap-3">
            <%= f.label :on_behalf_of_email, class: "block  text-sm text-white" %>
            <%= f.email_field :on_behalf_of_email, placeholder: "Enter behalf of email", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).on_behalf_of_email  %>
          </div>
          <div class="gap-3">
            <%= f.label :agency_license_number, class: "block  text-sm text-white" %>
            <%= f.text_field :agency_license_number, placeholder: "Enter agency license number", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).agency_license_number  %>
          </div>
          <div class="gap-3">
            <%= f.label :broker_license_number, class: "block  text-sm text-white" %>
            <%= f.text_field :broker_license_number, placeholder: "Enter broker license number", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).broker_license_number  %>
          </div>
          <div class="gap-3">
            <%= f.label :agency_address, class: "block  text-sm text-white" %>
            <%= f.text_field :agency_address, placeholder: "Enter address", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).agency_address  %>
          </div>
          <div class="gap-3">
            <%= f.label :agency_address_2, class: "block  text-sm text-white" %>
            <%= f.text_field :agency_address_2, placeholder: "Enter address 2", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).agency_address2  %>
          </div>
          <div class="gap-3">
            <%= f.label :agency_city, class: "block  text-sm text-white" %>
            <%= f.text_field :agency_city, placeholder: "Enter city", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).agency_city  %>
          </div>
          <div class="gap-3">
            <%= f.label :agency_state, class: "block  text-sm text-white" %>
            <%= f.text_field :agency_state, placeholder: "Enter Password", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).producer_id  %>
          </div>

          <div class="gap-3">
            <%= f.label :agency_zip_code, class: "block  text-sm text-white" %>
            <%= f.text_field :agency_zip_code, placeholder: "Enter zip code", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).agency_zip_code  %>
          </div>
          <div class="gap-3">
            <%= f.label :agency_phone_number, class: "block  text-sm text-white" %>
            <%= f.text_field :agency_phone_number, placeholder: "Enter Phone Number", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).agency_phone_numberd  %>
          </div>
          <div class="gap-3">
            <%= f.label :agency_fax_number, class: "block  text-sm text-white" %>
            <%= f.text_field :agency_fax_number, placeholder: "Enter Fax Number", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', value: current_user.settings(:agency_information).agency_fax_number  %>
          </div>
          <div class="gap-3">
            <%= f.submit "Update Agency Details", class: "w-full py-3 mt-6 font-medium tracking-widest text-white uppercase bg-black shadow-lg focus:outline-none hover:bg-gray-900 hover:shadow-none" %>
          </div>
        <% end %>


      </div>
    </div>
  </div>
</div>
<style>
  .login{
  /*
    background: url('https://tailwindadmin.netlify.app/dist/images/login-new.jpeg');
  */
  background: url('https://c4.wallpaperflare.com/wallpaper/467/696/839/blue-light-network-technology-wallpaper-thumb.jpg');
  background-repeat: no-repeat;
  background-size: cover;
}
</style>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>


<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
  <li>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                                    data: { confirm: "You sure?" } %>
    <% end %>
  </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>
<div class="h-screen font-sans login bg-cover">
<div class="container mx-auto h-full flex flex-1 justify-center items-center">
    <div class="w-full max-w-lg">
      <div class="leading-loose">
        <%= form_with(model: @user, local: true, class: "max-w-sm m-4 p-10 bg-white bg-opacity-25 rounded shadow-xl") do |f| %>
          <%= render 'shared/error_messages' %>
          <p class="text-white font-medium text-center text-lg font-bold">SIGN UP</p>
          <div class="gap-3">
            <span class="w-1/2">
              <%= f.label :name, class: "block  text-sm text-white" %>
              <%= f.text_field :name, placeholder: "Full Name", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner' %>
            </span>
            <span class="w-1/2">
              <%= f.label :agency, class: "block  text-sm text-white" %>
              <%= f.text_field :agency, placeholder: "Agency", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner' %>
            </span>
            <span class="w-1/2">
              <%= f.label :agency_code, class: 'block text-sm text-white' %>
              <%= f.text_field :agency_code, placeholder: 'Agency Code', class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner' %>
            </span>
          </div>
          <div class="gap-3">
            <%= f.label :email, class: "block  text-sm text-white" %>
            <%= f.email_field :email, class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner', required: true, autocomplete: "email", placeholder: "Enter your email" %>
          </div>
          <div class="gap-3">
            <%= f.label :password, class: "block  text-sm text-white" %>
            <%= f.password_field :password, placeholder: "Enter Password", autocomplete: "new-password", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner' %>
          </div>
          <div class="gap-3">
            <%= f.label :password_confirmation, "Confirmation", class: "block  text-sm text-white" %>
            <%= f.password_field :password_confirmation, placeholder: "Re-Enter Password", class: 'block w-full p-3 mt-2 text-gray-700 bg-gray-200 appearance-none focus:outline-none focus:bg-gray-300 focus:shadow-inner' %>
          </div>
          <div class="gap-3">
            <%= f.submit "Create my account", class: "w-full py-3 mt-6 font-medium tracking-widest text-white uppercase bg-black shadow-lg focus:outline-none hover:bg-gray-900 hover:shadow-none" %>
            <p class="flex justify-between inline-block mt-4 text-xs text-white cursor-pointer hover:text-black"><%= link_to "Already registered?", login_path %></p>
          </div>
        <% end %>


      </div>
    </div>
  </div>
</div>
<style>
  .login{
  /*
    background: url('https://tailwindadmin.netlify.app/dist/images/login-new.jpeg');
  */
  background: url('https://images.squarespace-cdn.com/content/v1/5b1c450a5ffd2031c58b74c1/1535860027471-WZ2TN6UV3QAV8WUTH74H/ke17ZwdGBToddI8pDm48kFTEgwhRQcX9r3XtU0e50sUUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcW7uEhC96WQdj-SwE5EpM0lAopPba9ZX3O0oeNTVSRxdHAmtcci_6bmVLoSDQq_pb/maxresdefault.jpg?format=2500w');
  background-repeat: no-repeat;
  background-size: cover;
}
</style>

app/views/users/show.html.erb
<div>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>

    <div x-data="{ sidebarOpen: false, darkMode: false }" :class="{ 'dark': darkMode }">
        <div class="flex h-screen bg-gray-100 dark:bg-gray-800 font-roboto">
            <div :class="sidebarOpen ? 'block' : 'hidden'" @click="sidebarOpen = false"
                class="fixed z-20 inset-0 bg-black opacity-50 transition-opacity lg:hidden"></div>

            <div :class="sidebarOpen ? 'translate-x-0 ease-out' : '-translate-x-full ease-in'"
                class="fixed z-30 inset-y-0 left-0 w-60 transition duration-300 transform bg-white dark:bg-gray-900 overflow-y-auto lg:translate-x-0 lg:static lg:inset-0">
                <div class="flex items-center justify-center mt-8">
                    <div class="flex items-center">
                        <span class="text-gray-800 dark:text-white text-2xl font-semibold">Your Portal</span>
                    </div>
                </div>

                <nav class="flex flex-col mt-10 px-4 text-center">
                    <a onclick="OverviewClick()"
                        class="mt-3 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-100  hover:bg-gray-200 dark:hover:bg-gray-800 rounded">About You</a>
                    <a onclick="CompletedAppsClick()"
                        class="mt-3 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-100  hover:bg-gray-200 dark:hover:bg-gray-800 rounded">Completed Applications</a>
                    <a onclick="NewAppsClick()"
                        class="mt-3 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-800 rounded">New Application</a>
                    <a onclick="MyProfileClick()"
                        class="mt-3 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-800 rounded">Settings</a>
                    <%= link_to "Edit Profile", edit_user_path(current_user), class: 'mt-3 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-800 rounded' %>
                    <% if current_user.admin? %>
                      <%= link_to "Admin Panel", admin_path, class: 'mt-3 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-100 hover:bg-gray-200 dark:hover:bg-gray-800 rounded' %>
                    <% end %>
                </nav>
            </div>

            <div class="flex-1 flex flex-col overflow-hidden">
                <header class="flex justify-between items-center p-6">
                    <div class="flex items-center space-x-4 lg:space-x-0">
                        <button @click="sidebarOpen = true"
                            class="text-gray-500 dark:text-gray-300 focus:outline-none lg:hidden">
                            <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M4 6H20M4 12H20M4 18H11" stroke="currentColor" stroke-width="2"
                                    stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </button>

                        <div>
                            <h1 class="text-2xl font-medium text-gray-800 dark:text-white">Your Agency: <%= current_user.agency %></h1>
                        </div>
                    </div>

                    <div class="flex items-center space-x-4">

                        <div x-data="{ dropdownOpen: false }" class="relative">
                            <button @click="dropdownOpen = ! dropdownOpen"
                                class="flex items-center space-x-2 relative focus:outline-none">
                                <h2 class="text-gray-700 dark:text-gray-300 text-sm hidden sm:block"><%= @user.name %></h2>
                                <img class="h-9 w-9 rounded-full border-2 border-purple-500 object-cover"
                                    src="https://images.unsplash.com/photo-1553267751-1c148a7280a1?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
                                    alt="Your avatar">
                            </button>

                            <div class="absolute right-0 mt-2 w-48 bg-white rounded-md overflow-hidden shadow-xl z-10"
                                x-show="dropdownOpen" x-transition:enter="transition ease-out duration-100 transform"
                                x-transition:enter-start="opacity-0 scale-95" x-transition:enter-end="opacity-100 scale-100"
                                x-transition:leave="transition ease-in duration-75 transform"
                                x-transition:leave-start="opacity-100 scale-100" x-transition:leave-end="opacity-0 scale-95"
                                @click.away="dropdownOpen = false">
                                <a onclick="OverviewClick()"
                                    class="block px-4 py-2 text-sm text-gray-700 hover:bg-purple-600 hover:text-white">About You</a>
                                <%= link_to 'Edit Profile', edit_user_path(current_user), class: 'block px-4 py-2 text-sm text-gray-700 hover:bg-purple-600 hover:text-white' %>
                                <%= link_to 'New Application', new_submission_path, class: 'block px-4 py-2 text-sm text-gray-700 hover:bg-purple-600 hover:text-white' %>
                                <% if current_user.admin? %>
                                  <%= link_to 'Admin Panel', admin_path, class: 'block px-4 py-2 text-sm text-gray-700 hover:bg-purple-600 hover:text-white' %>
                                <% end %>
                                <%= link_to 'Logout', logout_path, class: 'block px-4 py-2 text-sm text-gray-700 hover:bg-purple-600 hover:text-white' %>
                            </div>
                        </div>
                    </div>
                </header>

                <main class="flex-1 overflow-x-hidden overflow-y-auto">
                    <div class="container mx-auto px-6 py-8">
                        <div class="grid place-items-center h-96 text-gray-500 dark:text-gray-300 text-xl border-4 border-black-300 border-solid shadow-2xl">
                            <div id="OverviewDiv" style="display: none">
                              <h1 class="usr_info">
                                <p class="usr_info">Your Name:&nbsp;<%= @user.name %></p>
                                <p class="usr_info">Your Agency:&nbsp;<%= @user.agency %></p>
                                <p class="usr_info">Your Agency Code:&nbsp;<%= @user.agency_code %></p>
                                <p class="usr_info">Your Email:&nbsp;<%= @user.email %></p>
                        </div>
                        <div id="CompletedAppsDiv" style="display: none">
                          <h1 style="font-family: 'Cinzel', serif;'">
                            Your Completed Apps;<br/>
                             <%= @current_user.submissions %>
                          </h1>
                        </div>
                        <div id="NewAppDiv" style="display: none">
                          <h1>
                            Start a New Application;<br/>
                            <br/>
                            <%= link_to 'Applications', new_submission_path, class: 'bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded' %>
                          </h1>
                        </div>
                        <div id="MyProfileDiv" style="display: none">
                          <h1>
                            Edit Your Profile:
                          </h1>
                        </div>
                    </div>
                </main>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
  function OverviewClick()
  {
    var ov = document.getElementById("OverviewDiv");
    if (ov.style.display === "none")
    {
      ov.style.display = "block";
      document.getElementById("CompletedAppsDiv").style.display = "none";
      document.getElementById("NewAppDiv").style.display = "none";
      document.getElementById("MyProfileDiv").style.display = "none";
    }
    else
    {
      ov.style.display = "none";
    }
  }

  function CompletedAppsClick()
  {
    var ca = document.getElementById("CompletedAppsDiv");
    if (ca.style.display === "none")
    {
      ca.style.display = "block";
      document.getElementById("OverviewDiv").style.display = "none";
      document.getElementById("NewAppDiv").style.display = "none";
      document.getElementById("MyProfileDiv").style.display = "none";
    }
    else
    {
      ca.style.display = "none";
    }
  }

  function NewAppsClick()
  {
    var na = document.getElementById("NewAppDiv");
    if (na.style.display === "none")
    {
      na.style.display = "block";
      document.getElementById("OverviewDiv").style.display = "none";
      document.getElementById("CompletedAppsDiv").style.display = "none";
      document.getElementById("MyProfileDiv").style.display = "none";
    }
    else
    {
      na.style.display = "none";
    }
  }

  function MyProfileClick()
  {
    var mp = document.getElementById("MyProfileDiv");
    if (mp.style.display === "none")
    {
      mp.style.display = "block";
      document.getElementById("CompletedAppsDiv").style.display = "none";
      document.getElementById("NewAppDiv").style.display = "none";
      document.getElementById("OverviewDiv").style.display = "none";
    }
    else
    {
      mp.style.display = "none";
    }
  }
</script>