config/routes.rb
Rails.application.routes.draw do


  # Set Project Root Directory #
  root 'static_pages#home'

  # Set Project Base Pages #
  get 'about',     to: 'static_pages#about'
  get 'contact',   to: 'static_pages#contact'

  # Set User Directories #
  get    'signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'admin',    to: 'users#admin'
  get    'agency-information',   to: 'users#agency_information'
  post   'update-agency-information', to: 'users#rails_settings_setting_user', as: 'rails_settings_setting_user'
  patch   'update-agency-information', to: 'users#rails_settings_setting_user'

  # Set Project Resources #
  resources :users
  resources :submissions
  resources :business_infos
  get 'classcode/search', to: 'business_infos#search'

  post 'form-type', to: "submissions#form_type"
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  enum submission_type: [:commercial_liability, :general_liability, :in_land_marine]

end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/form_type.js.erb
<% if @type == "cpp" %>
$(".from-result").html("<%= escape_javascript(render'forms/general_liability') %>");
<% end %>

app/views/submissions/index.html.erb
<div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 pr-10 lg:px-8">
                <div class="align-middle rounded-tl-lg rounded-tr-lg inline-block w-full py-4 overflow-hidden bg-white shadow-lg px-12">
                    <div class="flex justify-between">
                        <div class="inline-flex border rounded w-7/12 px-2 lg:px-6 h-12 bg-transparent">
                            <div class="flex flex-wrap items-stretch w-full h-full mb-6 relative">
                                <div class="flex">
                                    <span class="flex items-center leading-normal bg-transparent rounded rounded-r-none border border-r-0 border-none lg:px-3 py-2 whitespace-no-wrap text-grey-dark text-sm">
                                        <svg width="18" height="18" class="w-4 lg:w-auto" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M8.11086 15.2217C12.0381 15.2217 15.2217 12.0381 15.2217 8.11086C15.2217 4.18364 12.0381 1 8.11086 1C4.18364 1 1 4.18364 1 8.11086C1 12.0381 4.18364 15.2217 8.11086 15.2217Z" stroke="#455A64" stroke-linecap="round" stroke-linejoin="round" />
                                            <path d="M16.9993 16.9993L13.1328 13.1328" stroke="#455A64" stroke-linecap="round" stroke-linejoin="round" />
                                        </svg>
                                    </span>
                                </div>
                                <input type="text" class="flex-shrink flex-grow flex-auto leading-normal tracking-wide w-px flex-1 border border-none border-l-0 rounded rounded-l-none px-3 relative focus:outline-none text-xxs lg:text-xs lg:text-base text-gray-500 font-thin" placeholder="Search">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="align-middle inline-block min-w-full shadow overflow-hidden bg-white shadow-dashboard px-8 pt-3 rounded-bl-lg rounded-br-lg">
                    <table class="min-w-full">
                        <thead>
                            <tr>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left leading-4 text-blue-500 tracking-wider">User ID:</th>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">User Name:</th>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">User Email:</th>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Agency:</th>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Status</th>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">Created At</th>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">View Application:</th>
                                <th class="px-6 py-3 border-b-2 border-gray-300"></th>
                            </tr>
                        </thead>
                        <tbody class="bg-white">
                          <% @submissions.each do |submission| %>
                                <tr>
                                    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500">
                                        <div class="flex items-center">
                                            <div>
                                                <div class="text-sm leading-5 text-gray-800">#<%= current_user.id %></div>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500">
                                        <div class="text-sm leading-5 text-blue-900">
                                          <%= current_user.name %>
                                        </div>
                                    </td>
                                    <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5"><%= current_user.email %></td>
                                    <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5"><%= current_user.agency %></td>
                                    <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">
                                        <span class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                                        <span aria-hidden class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                                        <span class="relative text-xs">active</span>
                                    </span>
                                    </td>
                                    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500 text-blue-900 text-sm leading-5"><%= Date.today %></td>
                                    <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-500 text-sm leading-5">
                                        <%= link_to "View Details",  submission_path(submission), class: "px-5 py-2 border-blue-500 border text-blue-500 rounded transition duration-300 hover:bg-blue-700 hover:text-white focus:outline-none"%>
                                    </td>
                          </tr>
                          <% end %>
                        </tbody>
                    </table>
                  <div class="sm:flex-1 sm:flex sm:items-center sm:justify-between mt-4 work-sans">
        <div>
            <p class="text-sm leading-5 text-blue-700">
                Showing
                <span class="font-medium">1</span>
                to
                <span class="font-medium">200</span>
                of
                <span class="font-medium">2000</span>
                results
            </p>
        </div>
        <div>
            <nav class="relative z-0 inline-flex shadow-sm">
                <div	>
                    <a href="#" class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm leading-5 font-medium text-gray-500 hover:text-gray-400 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-gray-500 transition ease-in-out duration-150" aria-label="Previous" v-on:click.prevent="changePage(pagination.current_page - 1)">
                        <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
                        </svg>
                    </a>
                </div>
                <div>
                    <a href="#" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm leading-5 font-medium text-blue-700 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-tertiary active:text-gray-700 transition ease-in-out duration-150 hover:bg-tertiary">
                        1
                    </a>
                  <a href="#" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm leading-5 font-medium text-blue-600 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-tertiary active:text-gray-700 transition ease-in-out duration-150 hover:bg-tertiary">
                        2
                    </a>
                   <a href="#" class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm leading-5 font-medium text-blue-600 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-tertiary active:text-gray-700 transition ease-in-out duration-150 hover:bg-tertiary">
                        3
                    </a>
                </div>
                <div v-if="pagination.current_page < pagination.last_page">
                    <a href="#" class="-ml-px relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm leading-5 font-medium text-gray-500 hover:text-gray-400 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-gray-500 transition ease-in-out duration-150" aria-label="Next">
                        <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                        </svg>
                    </a>
                </div>
            </nav>
        </div>
    </div>
                </div>
            </div>

app/views/submissions/new.html.erb
<div class="w-screen flex justify-center bg-gray-100">
  <div class="w-full mx-auto py-16">
    <!-- Title -->
    <h1 class="text-3xl text-center font-bold mb-6">
      Start buy selecting form
    </h1>
    <script type="text/javascript">
      $(document).on('load turbolinks:load', function () {
        $('.type-submit').on('click', function(event){
          event.preventDefault();
          type = $(this).data("type");
          $("#submission_type").val(type);
          form = document.querySelector('#set-form');
          form.dispatchEvent(new Event('submit', {bubbles: true}));
        });
        var options = {
          data: ["John", "Paul", "George", "Ringo"]
        };
        $('*[data-behavior="autocomplete"]').easyAutocomplete(options);
      });
    </script>
    <!-- End Title -->

    <!-- Default -->
    <div class="bg-white px-6 py-4 my-3 w-3/4 mx-auto shadow rounded-md flex items-center">
        <div class="w-full text-center mx-auto">
              <a href="#" data-type="cpp" class="type-submit border border-indigo-500 bg-indigo-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-indigo-600 focus:outline-none focus:shadow-outline">
                General liability
              </a>
              <a href="#" data-type="gl" class="type-submit border border-green-500 bg-green-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-green-600 focus:outline-none focus:shadow-outline">
                In-Land Marine
              </a>

              <%= form_with url: form_type_path, id: "set-form", local: false do |form| %>
               <%= form.hidden_field :submission_type, value: ""  %>
              <% end %>
        </div>
    </div>

    <div class="from-result form_holder" style="background-color: teal; ">

    </div>
    <!-- End Default -->
  </div>
</div>

app/views/submissions/show.html.erb
<div class="min-h-screen bg-gray-200 flex justify-center items-center">
   <div class="max-w-sm bg-white border-2 border-gray-300 p-6 rounded-md tracking-wide shadow-2xl">
      <div id="header" class="flex items-center mb-4">
         <img alt="avatar" class="w-20 rounded-full border-2 border-yellow-500" src="https://upload.wikimedia.org/wikipedia/en/7/72/Markel_Corporation_logo.jpg" />
         <div id="header-text" class="leading-5 ml-6 sm">
            <h4 id="name" class="text-xl font-semibold">Markel Insurance</h4>
            <h5 id="job" class="font-semibold text-yellow-500">Quote Section</h5>
         </div>
      </div>
      <div id="quote">
         <q class="italic text-red-600">
           <br/>
           <p>Policy ID: </p>
           <p>Final Premium: </p>
           <br/>
         </q><br/>
         <button class="bg-transparent hover:bg-yellow-500 text-yellow-700 font-semibold hover:text-white py-2 px-4 border border-yellow-500 hover:border-transparent rounded">Bind Markel</button>
         <button class="bg-transparent hover:bg-yellow-500 text-yellow-700 font-semibold hover:text-white py-2 px-4 border border-yellow-500 hover:border-transparent rounded">E-Mail</button>
      </div>
    </div>
    <div class="max-w-sm bg-white border-2 border-gray-300 p-6 rounded-md tracking-wide shadow-2xl">
      <div id="header" class="flex items-center mb-4">
        <img alt="IFG" class="w-20 rounded-full border-2 border-yellow-500" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ0osH8KBYgi8j0b-2o2-V1Qt15Vsgv-I_lg&usqp=CAU" />
        <div id="header-text" class="leading-5 ml-6 sm">
          <h4 id="name" class="text-xl font-semibold">IFG Insurance</h4>
          <h5 id="job" class="font-semibold text-lue-500">Quote Section</h5>
        </div>
      </div>
      <div id="quote">
        <q class="italic text-blue-600">
          <br/>
            <p>Policy ID:  <%= @policy_id  %></p>
            <p>Final Premium:  <%= @final_premium  %></p>
          <br/>
        </q><br/>
        <button class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">Bind IFG</button>
        <button class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">E-Mail</button>
      </div>
   </div>
</div>

<br/>
<br/>
<p style="font-size: 40px; text-align: center;">Complete Form Quote Details:</p>
<div style="padding: 20px; border: 3px solid; margin: 10px auto;">
  <%= @submission.data %>
</div>
<br/>
<br/>
<p style="font-size: 40px; text-align: center;">IFG Form Submission Results:</p>
<div style="padding: 20px; border: 3px solid #000; margin: 10px auto;">
  <%= @submission.ifg_result %>
</div>
<br/>
<br/>
<br/>
<p style="font-size: 40px; text-align: center;">Markel Form Submission Results:</p>
<div style="padding: 20px; border: 3px solid #00F; margin: 10px auto;">
  <%= @submission.markel_results %>
</div>