config/routes.rb
Rails.application.routes.draw do


  # Set Project Root Directory #
  root 'static_pages#home'

  # Set Project Base Pages #
  get 'about',     to: 'static_pages#about'
  get 'contact',   to: 'static_pages#contact'

  # Set User Directories #
  get    'signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'admin',    to: 'users#admin'
  get    'agency-information',   to: 'users#agency_information'
  post   'update-agency-information', to: 'users#rails_settings_setting_user', as: 'rails_settings_setting_user'
  patch   'update-agency-information', to: 'users#rails_settings_setting_user'

  # Set Project Resources #
  resources :users
  resources :submissions
  resources :business_infos
  get 'classcode/search', to: 'business_infos#search'

  post 'form-type', to: "submissions#form_type"
end

app/models/business_info.rb
class BusinessInfo < ApplicationRecord
end

app/controllers/business_infos_controller.rb
class BusinessInfosController < ApplicationController
  before_action :set_business_info, only: [:show, :edit, :update, :destroy]
  before_action :force_json, only: :search


  # GET /business_infos
  # GET /business_infos.json
  def index
    @business_infos = BusinessInfo.all
  end

  def search
    q = params[:q].downcase
    @business_infos = BusinessInfo.where("class_code ILIKE ? or business_type ILIKE ?", "%#{q}%", "%#{q}%").limit(5)
    # binding.pry
  end

  # GET /business_infos/1
  # GET /business_infos/1.json
  def show
  end

  # GET /business_infos/new
  def new
    @business_info = BusinessInfo.new
  end

  # GET /business_infos/1/edit
  def edit
  end

  # POST /business_infos
  # POST /business_infos.json
  def create
    @business_info = BusinessInfo.new(business_info_params)

    respond_to do |format|
      if @business_info.save
        format.html { redirect_to @business_info, notice: 'Business info was successfully created.' }
        format.json { render :show, status: :created, location: @business_info }
      else
        format.html { render :new }
        format.json { render json: @business_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_infos/1
  # PATCH/PUT /business_infos/1.json
  def update
    respond_to do |format|
      if @business_info.update(business_info_params)
        format.html { redirect_to @business_info, notice: 'Business info was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_info }
      else
        format.html { render :edit }
        format.json { render json: @business_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_infos/1
  # DELETE /business_infos/1.json
  def destroy
    @business_info.destroy
    respond_to do |format|
      format.html { redirect_to business_infos_url, notice: 'Business info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_info
      @business_info = BusinessInfo.find(params[:id])
      respond_to do |format|
        format.json { head :no_content }
      end
    end

    # Only allow a list of trusted parameters through.
    def business_info_params
      params.require(:business_info).permit(:business_type, :class_code)
    end

    def force_json
      request.format = :json
    end
end

app/helpers/business_infos_helper.rb
module BusinessInfosHelper
end

app/views/business_infos/_form.html.erb
<%= form_with(model: business_info) do |form| %>
  <% if business_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business_info.errors.count, "error") %> prohibited this business_info from being saved:</h2>

      <ul>
        <% business_info.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" align="center">
    <%= form.label :business_type %><br/>
    <%= form.text_field :business_type, style: 'border: 3px solid #000;; padding: 5px;' %>
  </div>
  <br/>

  <div class="field" align="center">
    <%= form.label :class_code %><br/>
    <%= form.text_field :class_code, style: 'border: 3px solid #000; padding: 5px;' %>
  </div>
<br/>
<br/>
  <div class="actions" align="center">
    <%= form.submit style: 'border: 3px solid #000; padding: 5px;' %>
  </div>
<% end %>

app/views/business_infos/edit.html.erb
<h1>Editing Business Info</h1>

<%= render 'form', business_info: @business_info %>

<%= link_to 'Show', @business_info %> |
<%= link_to 'Back', business_infos_path %>

app/views/business_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Business Infos</h1>
<%= link_to 'New Business Info', new_business_info_path %>

<table>
  <thead>
    <tr>
      <th>Business type</th>
      <th>Class code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_infos.each do |business_info| %>
      <tr>
        <td><%= business_info.business_type %></td>
        <td><%= business_info.class_code %></td>
        <td><%= link_to 'Show', business_info %></td>
        <td><%= link_to 'Edit', edit_business_info_path(business_info) %></td>
        <td><%= link_to 'Destroy', business_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business Info', new_business_info_path %>

app/views/business_infos/new.html.erb
<h1>New Business Info</h1>

<%= render 'form', business_info: @business_info %>

<%= link_to 'Back', business_infos_path %>

app/views/business_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business type:</strong>
  <%= @business_info.business_type %>
</p>

<p>
  <strong>Class code:</strong>
  <%= @business_info.class_code %>
</p>

<%= link_to 'Edit', edit_business_info_path(@business_info) %> |
<%= link_to 'Back', business_infos_path %> |
<%= link_to 'New Business Info', new_business_info_path %>