config/routes.rb
Rails.application.routes.draw do


  # Set Project Root Directory #
  root 'static_pages#home'

  # Set Project Base Pages #
  get 'about',     to: 'static_pages#about'
  get 'contact',   to: 'static_pages#contact'

  # Set User Directories #
  get    'signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'admin',    to: 'users#admin'
  get    'agency-information',   to: 'users#agency_information'
  post   'update-agency-information', to: 'users#rails_settings_setting_user', as: 'rails_settings_setting_user'
  patch   'update-agency-information', to: 'users#rails_settings_setting_user'

  # Set Project Resources #
  resources :users
  resources :submissions
  resources :business_infos
  get 'classcode/search', to: 'business_infos#search'

  post 'form-type', to: "submissions#form_type"
end

app/views/layouts/_footer.html.erb
<footer class="bg-gray-800 pt-10 pt-10">
    <div class="max-w-6xl m-auto text-gray-800 flex flex-wrap justify-left">
        <!-- Col-1 -->
        <div class="p-5 w-1/2 sm:w-4/12 md:w-3/12">
            <!-- Col Title -->
            <div class="text-xs uppercase text-gray-400 font-medium mb-6">
                Getting Started
            </div>

            <!-- Links -->
            <%= link_to 'Registration & Login', '#', class: "my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700" %>
            <%= link_to 'Quoting System', '#', class: "my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700" %>
            <%= link_to 'Navigation Assistance', '#', class: "my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700" %>
        </div>

        <!-- Col-2 -->
        <div class="p-5 w-1/2 sm:w-4/12 md:w-3/12">
            <!-- Col Title -->
            <div class="text-xs uppercase text-gray-400 font-medium mb-6">
                Core Resources
            </div>

            <!-- Links -->
            <%= link_to 'Ruby on Rails', 'https://rubyonrails.org/', class: "my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700", target: '_blank' %>
            <%= link_to 'Ubuntu Servers', 'https://ubuntu.com/', class: "my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700", target: '_blank' %>
            <%= link_to 'GitLab', 'https://about.gitlab.com/', target: '_blank', class: "my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700" %>
            <%= link_to 'PostgreSQL', 'https://www.postgresql.org/', target: '_blank', class: "my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700" %>
            <%= link_to 'Atom Text Editor', 'https://www.atom.io', target: '_blank', class: "my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700" %>
        </div>

        <!-- Col-3 -->
        <div class="p-5 w-1/2 sm:w-4/12 md:w-3/12">
            <!-- Col Title -->
            <div class="text-xs uppercase text-gray-400 font-medium mb-6">
                Community
            </div>

            <!-- Links -->
            <%= link_to 'Facebook', 'https://www.facebook.com', class: 'my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700', target: '_blank' %>
            <%= link_to 'Twitter', 'https://www.twitter.com', class: 'my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700', target: '_blank' %>
            <%= link_to 'LinkedIn', 'https://www.linkedin.com', class: 'my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700', target: '_blank' %>
            <%= link_to 'Minds', 'https://www.minds.com', class: 'my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700', target: '_blank' %>
            <%= link_to 'Tech Support', 'https://signal.group/#CjQKIMpR9i894OW2SKK0IBFA4xkFEHrc4Wjpei019cBWmAinEhAt_orPmuJJI1mY1mlxmkkX', class: 'my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700', target: '_blank' %>

        </div>
    </div>

    <!-- Copyright Bar -->
    <div class="pt-2">
        <div class="flex pb-5 px-3 m-auto pt-5
            border-t border-gray-500 text-gray-400 text-sm
            flex-col md:flex-row max-w-6xl">
            <div class="mt-2">
              Project Manager: <%= mail_to "brentd@texasspecialty.com", 'Brent Davis', style: 'cursor: crosshair' %><br/>
              Sr. Developer: <%= mail_to "cryp70@tuta.io", 'Cryp70', style: 'cursor: crosshair' %><br/>
              Developer: <%= mail_to "contact@kanyi.gm", 'Gh0s7', style: 'cursor: crosshair' %><br/>
              Sistering Company: <%= mail_to "info@texasspecialty.com", 'Texas Specialty Underwriters' %><br/>
              &copy; Copyright 2021 ~ <strong>PRESENT</strong>
            </div>

            <!-- Required Unicons (if you want) -->
            <div class="md:flex-auto md:flex-row-reverse mt-2 flex-row flex">
                <a href="#" class="w-6 mx-1">
                    <i class="uil uil-facebook-f"></i>
                </a>
                <a href="#" class="w-6 mx-1">
                    <i class="uil uil-twitter-alt"></i>
                </a>
                <a href="#" class="w-6 mx-1">
                    <i class="uil uil-youtube"></i>
                </a>
                <a href="#" class="w-6 mx-1">
                    <i class="uil uil-linkedin"></i>
                </a>
                <a href="#" class="w-6 mx-1">
                    <i class="uil uil-instagram"></i>
                </a>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav id="header" class="w-full z-30 py-1 shadow-lg border-b border-blue-400" style="background-color: #000">
      <div class="w-full flex items-center justify-between mt-0 px-6 py-2">
         <label for="menu-toggle" class="cursor-pointer md:hidden block">
            <svg class="fill-current text-blue-600" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
               <title>menu</title>
               <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
            </svg>
         </label>
         <input class="hidden" type="checkbox" id="menu-toggle">

         <div class="hidden md:flex md:items-center md:w-auto w-full order-3 md:order-1" id="menu">
            <nav>
               <ul class="md:flex items-center justify-between text-base text-blue-600 pt-4 md:pt-0">
                  <li><img src="https://i.gifer.com/7RwF.gif" class="inline-block no-underline hover:text-black font-medium text-lg py-2 px-4 lg:-ml-2" style="height: 75px; width: 100px;"></li>
                  <li><%= link_to "B1 Technologies", root_path, class: 'inline-block no-underline hover:text-black font-medium text-lg py-2 px-4 lg:-ml-2 nav_lnk' %></li>
                  <li><%= link_to 'Contact', contact_path, class: "inline-block no-underline hover:text-black font-medium text-lg py-2 px-4 lg:-ml-2 nav_lnk" %></li>
                  <li><%= link_to 'About', about_path, class: "inline-block no-underline hover:text-black font-medium text-lg py-2 px-4 lg:-ml-2 nav_lnk" %></li>
               </ul>
            </nav>
         </div>

         <div class="order-2 md:order-3 flex flex-wrap items-center justify-end mr-0 md:mr-4" id="nav-content">
            <div class="auth flex items-center w-full md:w-full">
               <% if logged_in? %>
                <%= link_to 'Logout', logout_path, method: :delete, class: "bg-red-600 text-yellow-200  p-2 rounded  hover:bg-yellow-500 hover:text-red-100", style: 'margin-right: 20px;' %>
                <%= link_to 'My Profile', current_user, class: 'bg-green-600 text-black-200  p-2 rounded  hover:bg-blue-500 hover:text-gray-100' %>
               <% else %>
                <%= link_to 'Register', signup_path, class: "bg-blue-600 text-gray-200  p-2 rounded  hover:bg-blue-500 hover:text-gray-100", style: "margin-right: 20px;" %>
                <%= link_to 'Login', login_path, class: "bg-green-600 text-gray-200  p-2 rounded  hover:bg-blue-500 hover:text-gray-100" %>
               <% end %>
            </div>
         </div>
      </div>
   </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/jquery.easy-autocomplete.min.js" integrity="sha512-Z/2pIbAzFuLlc7WIt/xifag7As7GuTqoBbLsVTgut69QynAIOclmweT6o7pkxVoGGfLcmPJKn/lnxyMNKBAKgg==" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/easy-autocomplete.min.css" integrity="sha512-TsNN9S3X3jnaUdLd+JpyR5yVSBvW9M6ruKKqJl5XiBpuzzyIMcBavigTAHaH50MJudhv5XIkXMOwBL7TbhXThQ==" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <!-- Import Font Awesome -->
    <script src="https://kit.fontawesome.com/160c7fc4e2.js" crossorigin="anonymous"></script>

    <!-- Import Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Audiowide&family=Black+Ops+One&family=Cinzel&family=Crimson+Text&family=IBM+Plex+Serif&family=Orbitron&family=Quantico&family=Righteous&family=Source+Code+Pro:wght@200&display=swap" rel="stylesheet">


    <!-- Import Google Tracking -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-X3H9HSJEBH"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-X3H9HSJEBH');
    </script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>